#pragma once

// GENERATED by tools/fit_cost_model.cpp. Do not edit by hand.
// Regenerate: cmake -DADM_FIT_COST_MODEL=ON, target admiral_cost_model.
//
// Routing cost model: one sparse linear model per form over structural
// features of N, predicting log(cycles). The route is argmin over forms, and
// exp is monotonic, so ranking needs no exponentiation.
//
// The coefficients are shared by every build: they describe the algorithm
// (radix content, lane waste, padding, footprint), so even a target this tool
// never swept routes on them, and nothing here is keyed to a machine. One
// slot is keyed to the COMPILER, which a machine key would not reach: gcc and
// clang price four_step against iterative_dif 1.25x apart on one host at one
// kernel vintage, and they move that pair in OPPOSITE directions at equal width.
// An unswept compiler takes the gcc branch. Every
// form is priced off what the engine actually runs: the measured PER-PRECISION
// leaf table (math.hpp) for codelet-terminated forms, the elected pad for
// Bluestein. A cell the coefficients still misprice is recovered by measuring at
// plan time (effort::automatic), not by a table that only covers swept machines.
//
// 38 coefficients. Route regret vs the exhaustive 2..512 sweep,
// in-sample max | out-of-fold:
//   x86_64 clang-18 f64 W= 2 regs=16: max 98.2%  |  median  0.0% p90   4.6% mean   2.3%
//   x86_64 clang-18 f32 W= 4 regs=16: max 123.4%  |  median  0.0% p90  20.3% mean   4.8%
//   x86_64 clang-18 f64 W= 4 regs=16: max 162.4%  |  median  0.0% p90   1.4% mean   3.3%
//   x86_64 clang-18 f32 W= 8 regs=16: max 92.5%  |  median  0.0% p90  16.5% mean   4.7%
//   x86_64 clang-18 f64 W= 8 regs=32: max 174.1%  |  median  0.0% p90  16.2% mean   5.8%
//   x86_64 clang-18 f32 W=16 regs=32: max 102.9%  |  median  0.0% p90   0.0% mean   1.8%
//   x86_64 clang-19 f64 W= 8 regs=32: max 126.4%  |  median  0.0% p90   0.0% mean   1.4%
//   x86_64 clang-19 f32 W=16 regs=32: max 74.1%  |  median  0.0% p90   0.0% mean   1.1%
//   x86_64 gcc-14 f64 W= 2 regs=16: max 128.4%  |  median  0.0% p90   0.0% mean   1.5%
//   x86_64 gcc-14 f32 W= 4 regs=16: max 95.6%  |  median  0.0% p90  23.1% mean   6.2%
//   x86_64 gcc-14 f64 W= 4 regs=16: max 120.1%  |  median  0.0% p90  11.7% mean   4.3%
//   x86_64 gcc-14 f64 W= 4 regs=16 uarch=znver2: max 88.8%  |  median  0.0% p90   3.7% mean   2.5%
//   x86_64 gcc-14 f32 W= 8 regs=16: max 209.4%  |  median  0.0% p90   0.0% mean   2.9%
//   x86_64 gcc-14 f32 W= 8 regs=16 uarch=znver2: max 103.1%  |  median  0.0% p90  38.4% mean   8.0%
//   x86_64 gcc-14 f64 W= 8 regs=32: max 136.4%  |  median  0.0% p90  16.4% mean   4.0%
//   x86_64 gcc-14 f64 W= 8 regs=32 uarch=sapphirerapids: max 49.1%  |  median  0.0% p90   0.0% mean   1.0%
//   x86_64 gcc-14 f32 W=16 regs=32: max 157.8%  |  median  0.0% p90   0.0% mean   1.9%
//   x86_64 gcc-14 f32 W=16 regs=32 uarch=sapphirerapids: max 52.9%  |  median  0.0% p90   0.0% mean   1.5%
//

#include <array>
#include <cstddef>
#include <cstdint>
#include <tuple>
#include <type_traits>
#include <utility>

#include <admiral/detail/build_id.hpp>
#include <admiral/detail/math.hpp>

namespace admiral::detail {

enum class base_form : std::uint8_t { codelet, iterative_dif, good_thomas,
                                      four_step, four_step_batched, rader, bluestein };

struct base_cost_entry {
    float cyc;   // modelled cycles (< 0 outside the modelled domain)
    base_form form;
};

inline constexpr std::size_t BASE_MODEL_NMIN = 2;
inline constexpr std::size_t BASE_MODEL_NMAX = 512;

namespace base_model {

// Width/precision environment: the only target properties the features read.
template<typename T>
struct env {
    static constexpr std::size_t Wi = build_width<T>;
    static constexpr double W = double(Wi);
    static constexpr double bytes = 2.0 * double(sizeof(T));
    static constexpr double vec(std::size_t m) { return double((m + Wi - 1) / Wi); }
    static constexpr double waste(std::size_t m) { return (vec(m) * W - double(m)) / W; }
};

// lpf_nfac, balanced_split and chain_work are NOT defined here: they live in
// math.hpp, and tools/fit_cost_model.cpp fits the coefficients below by calling
// those same definitions. A copy in this file would be a copy the lasso can
// silently disagree with, which is how a partial-chain clamp once mispriced
// 1355 of 2047 lengths. Only the <T> binding of W and the register count is
// local, because the fitter pools targets and cannot bind either.
template<typename T>
[[nodiscard]] constexpr double chain_work(std::size_t n) {
    return admiral::detail::chain_work(n, env<T>::Wi, build_vector_regs);
}

// Every form also carries log2(W), log(bytes per element pair) and a clang
// indicator. The two compilers price four_step against iterative_dif 1.25x
// apart on one host at one kernel vintage, and that pair is the dominant route
// below 512; an unswept compiler takes the gcc branch.
template<typename T, std::size_t K>
[[nodiscard]] constexpr std::array<double, K + 3> with_tail(const std::array<double, K>& a) {
    std::array<double, K + 3> f{};
    for (std::size_t i = 0; i < K; ++i) f[i] = a[i];
    f[K]     = ct_log2(env<T>::W);
    f[K + 1] = ct_log2(env<T>::bytes) / ct_log2(2.7182818284590452354);
    f[K + 2] = build_compiler == "clang" ? 1.0 : 0.0;
    return f;
}

// One class per form, each priced from ITS OWN sub-problem: bluestein and
// rader from the padded length M, four_step from its split, iterative_dif from
// its radix chain. The coefficient array is sized to that form's feature
// vector, so a mismatch is a compile error rather than a silent misread.

struct codelet {
    static constexpr base_form tag = base_form::codelet;
    static constexpr double bias = 1.3585945271309894;
    // log2(n), log2(leaf_cyc), vec, lane_waste, n_factors, log2(lpf), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 9> w = {
        0.09012900452310776, 0.4623839845795388, 0.016749058074134262, 0.0, 0.0,
        0.05032943800346652, 0.0, 0.0, -0.09695976468665471,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 9> features(std::size_t n) {
        using e = env<T>;
        const auto [lpf, nfac] = lpf_nfac(n);
        return with_tail<T>(std::array<double, 6>{
            ct_log2(double(n)),
            ct_log2(leaf_cost_cyc<T>(n)),
            e::vec(n),
            e::waste(n),
            double(nfac),
            ct_log2(double(lpf)),
        });
    }
};

struct iterative_dif {
    static constexpr base_form tag = base_form::iterative_dif;
    static constexpr double bias = 2.88524763020275;
    // log2(n), chainwork, chainwork*log2(n), n_factors, log2(lpf), lane_waste(lpf), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 9> w = {
        0.43820386866475536, 0.0, 0.0020535547130466195, 0.0, 0.22070383881087738, 0.0, 0.0,
        0.030732415702841888, 0.0,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 9> features(std::size_t n) {
        using e = env<T>;
        const auto [lpf, nfac] = lpf_nfac(n);
        const double cw = chain_work<T>(n);
        return with_tail<T>(std::array<double, 6>{
            ct_log2(double(n)),
            cw,
            cw * ct_log2(double(n)),
            double(nfac),
            ct_log2(double(lpf)),
            e::waste(lpf),
        });
    }
};

struct good_thomas {
    static constexpr base_form tag = base_form::good_thomas;
    static constexpr double bias = 2.983103271700825;
    // log2(n), n2*vec(n1)/n1, n2*vec(n1), n1*vec(n2), log2(n1), log2(n2), lane_waste(n1), lane_waste(n2), n/W, log2(four_step_cost), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 13> w = {
        0.16284464352859548, 0.0, 0.0, 0.0, 0.0, 0.05706582467934254, 0.0, 0.0,
        0.06555959451265599, 0.09163401180507977, 0.0, 0.0, -0.07370091659046954,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 13> features(std::size_t n) {
        using e = env<T>;
        const auto [n1, n2] = balanced_split(n);
        return with_tail<T>(std::array<double, 10>{
            ct_log2(double(n)),
            e::vec(n1) * double(n2) / double(n1),
            double(n2) * e::vec(n1),
            double(n1) * e::vec(n2),
            ct_log2(double(n1)),
            ct_log2(double(n2)),
            e::waste(n1),
            e::waste(n2),
            double(n) / e::W,
            ct_log2(four_step_cost<T>(n1, n2)),
        });
    }
};

struct four_step {
    static constexpr base_form tag = base_form::four_step;
    static constexpr double bias = 2.4400055528738553;
    // log2(n), n2*vec(n1)/n1, n2*vec(n1), n1*vec(n2), log2(n1), log2(n2), lane_waste(n1), lane_waste(n2), n/W, log2(four_step_cost), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 13> w = {
        0.1356340890131949, 0.0, 0.0009572244499606585, 0.0, 0.0, 0.11338676096267923, 0.0, 0.0,
        0.0, 0.3799991043386408, 0.0, 0.0, -0.2290031124634066,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 13> features(std::size_t n) {
        using e = env<T>;
        const auto [n1, n2] = balanced_split(n);
        return with_tail<T>(std::array<double, 10>{
            ct_log2(double(n)),
            e::vec(n1) * double(n2) / double(n1),
            double(n2) * e::vec(n1),
            double(n1) * e::vec(n2),
            ct_log2(double(n1)),
            ct_log2(double(n2)),
            e::waste(n1),
            e::waste(n2),
            double(n) / e::W,
            ct_log2(four_step_cost<T>(n1, n2)),
        });
    }
};

struct rader {
    static constexpr base_form tag = base_form::rader;
    static constexpr double bias = 3.692587978825538;
    // log2(n), log2(L), chainwork(L), chainwork(L)*log2(L), vec(L), lane_waste(L), n_factors(L), log2(lpf(L)), no_chain(L), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 12> w = {
        0.0, 0.6068274788441181, 0.0, 4.2423542361037304e-05, 0.0015035409836936472,
        0.04954426490770766, -0.06178900572675743, 0.06362342828377744, 0.9689598977298833,
        -0.042084007239494806, 0.0, -0.11231787275475227,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 12> features(std::size_t n) {
        using e = env<T>;
        const std::size_t L = n > 2 ? n - 1 : 1;
        const double cw = chain_work<T>(L);
        return with_tail<T>(std::array<double, 9>{
            ct_log2(double(n)),
            ct_log2(double(L)),
            cw,
            cw * ct_log2(double(L)),
            e::vec(L),
            e::waste(L),
            double(lpf_nfac(L)[1]),
            ct_log2(double(lpf_nfac(L)[0])),
            cw == 0.0 && L > 1 ? 1.0 : 0.0,
        });
    }
};

struct bluestein {
    static constexpr base_form tag = base_form::bluestein;
    static constexpr double bias = 3.98253758795364;
    // log2(n), log2(M), M/n, chainwork(M), chainwork(M)*log2(M), vec(M), lane_waste(M), n_factors(M), log2(W), log(bytes), is_clang
    static constexpr std::array<double, 11> w = {
        0.5845518600309761, 0.0, 0.0, 0.005699361313442483, 0.0, 0.0, 0.0, 0.0,
        -0.1983077226320634, 0.22755954007287954, 0.0,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 11> features(std::size_t n) {
        using e = env<T>;
        const std::size_t m = bluestein_choose_pad(n);
        const double cw = chain_work<T>(m);
        return with_tail<T>(std::array<double, 8>{
            ct_log2(double(n)),
            ct_log2(double(m)),
            double(m) / double(n),
            cw,
            cw * ct_log2(double(m)),
            e::vec(m),
            e::waste(m),
            double(lpf_nfac(m)[1]),
        });
    }
};

using forms = std::tuple<codelet, iterative_dif, good_thomas, four_step, rader, bluestein>;
inline constexpr std::size_t NFORM = std::tuple_size_v<forms>;

template<typename M, typename T>
[[nodiscard]] constexpr double score(std::size_t n) {
    const auto x = M::template features<T>(n);
    static_assert(std::tuple_size_v<std::remove_cvref_t<decltype(x)>> ==
                  std::tuple_size_v<std::remove_cvref_t<decltype(M::w)>>,
                  "feature/coefficient count mismatch");
    double acc = M::bias;
    for (std::size_t i = 0; i < x.size(); ++i) acc += M::w[i] * x[i];
    return acc;
}

template<typename T, std::size_t... I>
[[nodiscard]] constexpr auto score_all(std::size_t n, std::index_sequence<I...>) {
    return std::array<double, sizeof...(I)>{score<std::tuple_element_t<I, forms>, T>(n)...};
}

template<std::size_t... I>
[[nodiscard]] constexpr auto tags(std::index_sequence<I...>) {
    return std::array<base_form, sizeof...(I)>{std::tuple_element_t<I, forms>::tag...};
}

}  // namespace base_model

// Ranked routes for n, cheapest modelled first. The caller walks the ranking
// and takes the first buildable route, so an unavailable winner degrades to
// the model's next choice rather than falling out of the model entirely.
struct base_model_ranking {
    std::array<base_form, base_model::NFORM> form{};
    // form[k]'s score, in LOG cycles. Kept unexponentiated: only best_cyc is ever
    // needed in cycles, and one std::exp per form would cost the ranking more than
    // it sorts. dbg_cost tracing exponentiates on its own cold path.
    std::array<float, base_model::NFORM> log_cyc{};
    std::size_t count = 0;
    float best_cyc = -1.f;
};

// Form names for dbg_cost tracing.
[[nodiscard]] constexpr const char* base_form_name(base_form f) noexcept {
    switch (f) {
    case base_form::codelet:           return "codelet";
    case base_form::iterative_dif:     return "iterative_dif";
    case base_form::good_thomas:       return "good_thomas";
    case base_form::four_step:         return "four_step";
    case base_form::four_step_batched: return "four_step_batched";
    case base_form::rader:             return "rader";
    case base_form::bluestein:         return "bluestein";
    }
    return "?";
}

// Scored with ct_log2/ct_exp's series rather than libm, so routing is bitwise
// identical across libm versions. Only the table below calls it.
template<typename T>
[[nodiscard]] constexpr base_model_ranking score_ranking(std::size_t n) {
    using namespace base_model;
    base_model_ranking out;
    if (n < BASE_MODEL_NMIN || n > BASE_MODEL_NMAX) return out;

    constexpr auto seq = std::make_index_sequence<NFORM>{};
    const auto z = score_all<T>(n, seq);
    constexpr auto tag = tags(seq);

    // selection sort on log-cost: NFORM is small, and this must stay constexpr.
    std::array<bool, NFORM> used{};
    for (std::size_t k = 0; k < NFORM; ++k) {
        std::size_t bi = NFORM;
        for (std::size_t f = 0; f < NFORM; ++f)
            if (!used[f] && (bi == NFORM || z[f] < z[bi])) bi = f;
        used[bi] = true;
        out.form[k] = tag[bi];
        out.log_cyc[k] = float(z[bi]);
        if (k == 0) out.best_cyc = float(ct_exp(z[bi]));
    }
    out.count = NFORM;
    return out;
}

// Ranked routes for n, cheapest modelled first; count == 0 outside the domain.
//
// Filled on first use, not by the compiler: as a constexpr table this exceeded
// clang's default -fconstexpr-steps and cost seconds of constant evaluation in
// every TU that routes. Slots below NMIN stay value-initialised, so an
// out-of-domain n reads slot 0 and reports count == 0 without a second branch.
template<typename T>
[[nodiscard]] inline const base_model_ranking& base_route_ranking(std::size_t n) {
    static const std::array<base_model_ranking, BASE_MODEL_NMAX + 1> table = [] {
        std::array<base_model_ranking, BASE_MODEL_NMAX + 1> t{};
        for (std::size_t i = BASE_MODEL_NMIN; i <= BASE_MODEL_NMAX; ++i) t[i] = score_ranking<T>(i);
        return t;
    }();
    return table[n <= BASE_MODEL_NMAX ? n : 0];
}

// Best modelled route for n; cyc < 0 outside the modelled domain.
// Retained for --decomp-report; routing uses base_route_ranking.
template<typename T>
[[nodiscard]] inline base_cost_entry base_cost_for(std::size_t n) noexcept {
    const auto& r = base_route_ranking<T>(n);
    if (r.count == 0) return {-1.f, base_form::codelet};
    return {r.best_cyc, r.form[0]};
}

}  // namespace admiral::detail
