// GENERATED by scripts/gen_base_cost_table.py from bench-results/base_cost_*.txt
// do not edit by hand; rerun the script to refresh.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <xsimd/xsimd.hpp>

namespace admiral::detail {

enum class base_form : std::uint8_t { codelet, iterative_dif, good_thomas };

struct base_cost_entry {
    float cyc;
    base_form form;
};  // cyc<0 = no entry

// base_cost_for<T>(n): measured cycle count and winning form for transform
// size n (2..64, plus catalog extras like 120) on the current ISA.  Returns
// cyc<0 for unmeasured cells (n==0, unmeasured n>64, or sizes where only the
// force-route path was tried).
//
// Source receipts: bench-results/base_cost_{v4,v3,v2}.txt
// (see also bench-results/pfa_smalln_ab_raw.txt for earlier PFA A/B data).
// Winner rule: min-cyc form; margin: runner-up must cost >=3% more,
// otherwise cell falls back to the plan.hpp incumbent routing.
template<typename T>
[[nodiscard]] constexpr base_cost_entry base_cost_for(std::size_t n) noexcept {
    constexpr base_cost_entry NO_ENTRY{-1.f, base_form::codelet};
    if (n == 0) return NO_ENTRY;
    if constexpr (sizeof(T) == 4 && xsimd::batch<T>::size == 16) {
        // v4 f32 W=16
        if (n == 120) return {403.3f, base_form::codelet};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v4_f32 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {14.5f, base_form::codelet},  // n=2
            {15.0f, base_form::codelet},  // n=3
            {15.9f, base_form::codelet},  // n=4
            {16.8f, base_form::codelet},  // n=5
            {19.4f, base_form::codelet},  // n=6
            {70.2f, base_form::codelet},  // n=7
            {23.2f, base_form::codelet},  // n=8
            {64.2f, base_form::codelet},  // n=9
            {40.2f, base_form::codelet},  // n=10
            {115.6f, base_form::codelet},  // n=11
            {48.0f, base_form::codelet},  // n=12
            {149.0f, base_form::codelet},  // n=13
            {131.9f, base_form::iterative_dif},  // n=14
            {88.1f, base_form::good_thomas},  // n=15
            {91.0f, base_form::codelet},  // n=16
            {257.3f, base_form::codelet},  // n=17
            {121.5f, base_form::iterative_dif},  // n=18
            {399.6f, base_form::codelet},  // n=19
            {73.3f, base_form::codelet},  // n=20
            {139.4f, base_form::codelet},  // n=21
            {149.6f, base_form::iterative_dif},  // n=22
            {570.7f, base_form::codelet},  // n=23
            {144.8f, base_form::good_thomas},  // n=24
            {157.2f, base_form::iterative_dif},  // n=25
            {290.7f, base_form::codelet},  // n=26
            {140.8f, base_form::iterative_dif},  // n=27
            {150.2f, base_form::codelet},  // n=28
            {429.6f, base_form::codelet},  // n=29
            {99.8f, base_form::good_thomas},  // n=30
            {594.1f, base_form::codelet},  // n=31
            {174.2f, base_form::codelet},  // n=32
            {210.3f, base_form::codelet},  // n=33
            {538.5f, base_form::codelet},  // n=34
            {205.5f, base_form::codelet},  // n=35
            {151.0f, base_form::iterative_dif},  // n=36
            {424.7f, base_form::codelet},  // n=37
            {847.2f, base_form::codelet},  // n=38
            {247.0f, base_form::codelet},  // n=39
            {117.5f, base_form::good_thomas},  // n=40
            {454.0f, base_form::codelet},  // n=41
            {340.0f, base_form::iterative_dif},  // n=42
            {991.2f, base_form::codelet},  // n=43
            {182.7f, base_form::iterative_dif},  // n=44
            {199.4f, base_form::iterative_dif},  // n=45
            {1176.8f, base_form::codelet},  // n=46
            {2446.8f, base_form::codelet},  // n=47
            {172.6f, base_form::iterative_dif},  // n=48
            {286.7f, base_form::codelet},  // n=49
            {371.4f, base_form::codelet},  // n=50
            {323.8f, base_form::codelet},  // n=51
            {235.0f, base_form::codelet},  // n=52
            {662.5f, base_form::codelet},  // n=53
            {205.9f, base_form::codelet},  // n=54
            {227.6f, base_form::codelet},  // n=55
            {233.8f, base_form::codelet},  // n=56
            {402.8f, base_form::codelet},  // n=57
            {838.1f, base_form::codelet},  // n=58
            {1741.9f, base_form::codelet},  // n=59
            {155.7f, base_form::good_thomas},  // n=60
            {623.2f, base_form::codelet},  // n=61
            {1160.7f, base_form::codelet},  // n=62
            {238.1f, base_form::iterative_dif},  // n=63
            {159.9f, base_form::codelet}  // n=64
        }};
        return tab_v4_f32[n];
    }
    else if constexpr (sizeof(T) == 8 && xsimd::batch<T>::size == 8) {
        // v4 f64 W=8
        if (n == 120) return {459.5f, base_form::iterative_dif};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v4_f64 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {15.7f, base_form::codelet},  // n=2
            {16.7f, base_form::codelet},  // n=3
            {18.2f, base_form::codelet},  // n=4
            {19.4f, base_form::codelet},  // n=5
            {25.0f, base_form::codelet},  // n=6
            {79.2f, base_form::codelet},  // n=7
            {23.1f, base_form::codelet},  // n=8
            {45.9f, base_form::codelet},  // n=9
            {40.7f, base_form::codelet},  // n=10
            {124.3f, base_form::codelet},  // n=11
            {44.9f, base_form::good_thomas},  // n=12
            {171.9f, base_form::codelet},  // n=13
            {61.4f, base_form::codelet},  // n=14
            {75.5f, base_form::codelet},  // n=15
            {91.2f, base_form::codelet},  // n=16
            {277.9f, base_form::codelet},  // n=17
            {82.1f, base_form::codelet},  // n=18
            {275.1f, base_form::codelet},  // n=19
            {74.9f, base_form::good_thomas},  // n=20
            {162.4f, base_form::iterative_dif},  // n=21
            {156.9f, base_form::iterative_dif},  // n=22
            {516.2f, base_form::codelet},  // n=23
            {110.7f, base_form::good_thomas},  // n=24
            {157.5f, base_form::iterative_dif},  // n=25
            {226.8f, base_form::codelet},  // n=26
            {161.5f, base_form::iterative_dif},  // n=27
            {159.5f, base_form::codelet},  // n=28
            {348.0f, base_form::codelet},  // n=29
            {151.4f, base_form::good_thomas},  // n=30
            {503.4f, base_form::codelet},  // n=31
            {240.8f, base_form::codelet},  // n=32
            {193.9f, base_form::iterative_dif},  // n=33
            {296.8f, base_form::codelet},  // n=34
            {206.8f, base_form::iterative_dif},  // n=35
            {189.6f, base_form::iterative_dif},  // n=36
            {428.2f, base_form::codelet},  // n=37
            {422.5f, base_form::codelet},  // n=38
            {291.2f, base_form::codelet},  // n=39
            {148.9f, base_form::iterative_dif},  // n=40
            {556.8f, base_form::codelet},  // n=41
            {279.4f, base_form::iterative_dif},  // n=42
            {684.7f, base_form::codelet},  // n=43
            {216.2f, base_form::iterative_dif},  // n=44
            {261.6f, base_form::codelet},  // n=45
            {573.1f, base_form::codelet},  // n=46
            {1135.9f, base_form::codelet},  // n=47
            {198.2f, base_form::iterative_dif},  // n=48
            {283.7f, base_form::iterative_dif},  // n=49
            {346.0f, base_form::iterative_dif},  // n=50
            {385.3f, base_form::codelet},  // n=51
            {354.1f, base_form::codelet},  // n=52
            {775.1f, base_form::codelet},  // n=53
            {276.5f, base_form::iterative_dif},  // n=54
            {278.9f, base_form::codelet},  // n=55
            {210.5f, base_form::iterative_dif},  // n=56
            {486.5f, base_form::codelet},  // n=57
            {606.1f, base_form::codelet},  // n=58
            {1297.9f, base_form::codelet},  // n=59
            {255.5f, base_form::iterative_dif},  // n=60
            {724.1f, base_form::codelet},  // n=61
            {701.1f, base_form::codelet},  // n=62
            {256.0f, base_form::iterative_dif},  // n=63
            {204.1f, base_form::iterative_dif}  // n=64
        }};
        return tab_v4_f64[n];
    }
    else if constexpr (sizeof(T) == 4 && xsimd::batch<T>::size == 8) {
        // v3 f32 W=8
        if (n == 120) return {310.7f, base_form::iterative_dif};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v3_f32 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {18.9f, base_form::codelet},  // n=2
            {19.4f, base_form::codelet},  // n=3
            {19.6f, base_form::codelet},  // n=4
            {20.2f, base_form::codelet},  // n=5
            {22.3f, base_form::codelet},  // n=6
            {75.9f, base_form::codelet},  // n=7
            {25.2f, base_form::codelet},  // n=8
            {60.6f, base_form::codelet},  // n=9
            {97.6f, base_form::good_thomas},  // n=10
            {135.6f, base_form::codelet},  // n=11
            {56.5f, base_form::good_thomas},  // n=12
            {165.4f, base_form::codelet},  // n=13
            {111.1f, base_form::iterative_dif},  // n=14
            {140.7f, base_form::good_thomas},  // n=15
            {57.3f, base_form::codelet},  // n=16
            {161.0f, base_form::codelet},  // n=17
            {147.9f, base_form::codelet},  // n=18
            {366.4f, base_form::codelet},  // n=19
            {123.8f, base_form::good_thomas},  // n=20
            {136.9f, base_form::codelet},  // n=21
            {153.0f, base_form::iterative_dif},  // n=22
            {607.8f, base_form::codelet},  // n=23
            {171.7f, base_form::iterative_dif},  // n=24
            {166.7f, base_form::iterative_dif},  // n=25
            {313.1f, base_form::codelet},  // n=26
            {162.3f, base_form::codelet},  // n=27
            {153.7f, base_form::codelet},  // n=28
            {340.0f, base_form::codelet},  // n=29
            {210.1f, base_form::good_thomas},  // n=30
            {571.9f, base_form::codelet},  // n=31
            {124.3f, base_form::iterative_dif},  // n=32
            {176.8f, base_form::iterative_dif},  // n=33
            {325.6f, base_form::codelet},  // n=34
            {208.5f, base_form::codelet},  // n=35
            {187.6f, base_form::codelet},  // n=36
            {386.1f, base_form::codelet},  // n=37
            {775.8f, base_form::codelet},  // n=38
            {273.6f, base_form::codelet},  // n=39
            {138.7f, base_form::iterative_dif},  // n=40
            {453.9f, base_form::codelet},  // n=41
            {217.4f, base_form::iterative_dif},  // n=42
            {958.9f, base_form::codelet},  // n=43
            {185.8f, base_form::iterative_dif},  // n=44
            {246.3f, base_form::codelet},  // n=45
            {1226.6f, base_form::codelet},  // n=46
            {2410.0f, base_form::codelet},  // n=47
            {148.7f, base_form::iterative_dif},  // n=48
            {292.0f, base_form::iterative_dif},  // n=49
            {265.2f, base_form::iterative_dif},  // n=50
            {352.8f, base_form::codelet},  // n=51
            {256.6f, base_form::codelet},  // n=52
            {613.4f, base_form::codelet},  // n=53
            {244.7f, base_form::codelet},  // n=54
            {232.3f, base_form::iterative_dif},  // n=55
            {184.1f, base_form::iterative_dif},  // n=56
            {495.0f, base_form::codelet},  // n=57
            {605.6f, base_form::codelet},  // n=58
            {1287.2f, base_form::codelet},  // n=59
            {234.8f, base_form::codelet},  // n=60
            {577.9f, base_form::codelet},  // n=61
            {1070.1f, base_form::codelet},  // n=62
            {311.0f, base_form::codelet},  // n=63
            {172.8f, base_form::iterative_dif}  // n=64
        }};
        return tab_v3_f32[n];
    }
    else if constexpr (sizeof(T) == 8 && xsimd::batch<T>::size == 4) {
        // v3 f64 W=4
        if (n == 120) return {583.0f, base_form::iterative_dif};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v3_f64 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {20.2f, base_form::codelet},  // n=2
            {20.4f, base_form::codelet},  // n=3
            {20.1f, base_form::codelet},  // n=4
            {22.2f, base_form::codelet},  // n=5
            {24.6f, base_form::codelet},  // n=6
            {82.8f, base_form::codelet},  // n=7
            {21.6f, base_form::codelet},  // n=8
            {43.3f, base_form::codelet},  // n=9
            {75.0f, base_form::good_thomas},  // n=10
            {136.0f, base_form::codelet},  // n=11
            {85.6f, base_form::good_thomas},  // n=12
            {169.9f, base_form::codelet},  // n=13
            {130.3f, base_form::codelet},  // n=14
            {133.4f, base_form::good_thomas},  // n=15
            {103.2f, base_form::iterative_dif},  // n=16
            {169.5f, base_form::codelet},  // n=17
            {139.5f, base_form::codelet},  // n=18
            {302.0f, base_form::codelet},  // n=19
            {151.7f, base_form::good_thomas},  // n=20
            {133.7f, base_form::iterative_dif},  // n=21
            {195.1f, base_form::codelet},  // n=22
            {475.8f, base_form::codelet},  // n=23
            {174.0f, base_form::good_thomas},  // n=24
            {180.2f, base_form::iterative_dif},  // n=25
            {274.3f, base_form::codelet},  // n=26
            {186.9f, base_form::codelet},  // n=27
            {154.8f, base_form::iterative_dif},  // n=28
            {342.7f, base_form::codelet},  // n=29
            {251.6f, base_form::good_thomas},  // n=30
            {465.1f, base_form::codelet},  // n=31
            {143.8f, base_form::iterative_dif},  // n=32
            {264.7f, base_form::codelet},  // n=33
            {380.1f, base_form::codelet},  // n=34
            {212.0f, base_form::iterative_dif},  // n=35
            {180.0f, base_form::iterative_dif},  // n=36
            {412.3f, base_form::codelet},  // n=37
            {465.4f, base_form::codelet},  // n=38
            {358.5f, base_form::codelet},  // n=39
            {185.9f, base_form::iterative_dif},  // n=40
            {748.9f, base_form::codelet},  // n=41
            {265.2f, base_form::iterative_dif},  // n=42
            {735.6f, base_form::codelet},  // n=43
            {287.4f, base_form::codelet},  // n=44
            {287.3f, base_form::codelet},  // n=45
            {589.1f, base_form::codelet},  // n=46
            {1314.3f, base_form::codelet},  // n=47
            {242.6f, base_form::iterative_dif},  // n=48
            {282.1f, base_form::iterative_dif},  // n=49
            {320.2f, base_form::iterative_dif},  // n=50
            {421.5f, base_form::codelet},  // n=51
            {371.9f, base_form::codelet},  // n=52
            {863.5f, base_form::codelet},  // n=53
            {413.5f, base_form::codelet},  // n=54
            {316.9f, base_form::iterative_dif},  // n=55
            {264.7f, base_form::iterative_dif},  // n=56
            {537.0f, base_form::codelet},  // n=57
            {670.9f, base_form::codelet},  // n=58
            {1553.4f, base_form::codelet},  // n=59
            {274.0f, base_form::iterative_dif},  // n=60
            {749.9f, base_form::codelet},  // n=61
            {789.4f, base_form::codelet},  // n=62
            {332.7f, base_form::iterative_dif},  // n=63
            {272.5f, base_form::iterative_dif}  // n=64
        }};
        return tab_v3_f64[n];
    }
    else if constexpr (sizeof(T) == 4 && xsimd::batch<T>::size == 4) {
        // v2 f32 W=4
        if (n == 120) return {452.4f, base_form::iterative_dif};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v2_f32 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {20.7f, base_form::codelet},  // n=2
            {17.9f, base_form::codelet},  // n=3
            {21.3f, base_form::codelet},  // n=4
            {20.2f, base_form::codelet},  // n=5
            {23.5f, base_form::codelet},  // n=6
            {56.3f, base_form::codelet},  // n=7
            {23.5f, base_form::codelet},  // n=8
            {63.7f, base_form::codelet},  // n=9
            {74.3f, base_form::codelet},  // n=10
            {112.7f, base_form::codelet},  // n=11
            {50.6f, base_form::codelet},  // n=12
            {155.3f, base_form::codelet},  // n=13
            {121.5f, base_form::codelet},  // n=14
            {98.7f, base_form::iterative_dif},  // n=15
            {80.4f, base_form::iterative_dif},  // n=16
            {161.1f, base_form::codelet},  // n=17
            {155.3f, base_form::codelet},  // n=18
            {359.3f, base_form::codelet},  // n=19
            {100.8f, base_form::iterative_dif},  // n=20
            {143.2f, base_form::codelet},  // n=21
            {218.8f, base_form::codelet},  // n=22
            {486.7f, base_form::codelet},  // n=23
            {106.3f, base_form::iterative_dif},  // n=24
            {145.9f, base_form::iterative_dif},  // n=25
            {303.8f, base_form::codelet},  // n=26
            {155.1f, base_form::codelet},  // n=27
            {123.9f, base_form::iterative_dif},  // n=28
            {340.0f, base_form::codelet},  // n=29
            {268.3f, base_form::codelet},  // n=30
            {592.5f, base_form::codelet},  // n=31
            {107.9f, base_form::iterative_dif},  // n=32
            {240.4f, base_form::codelet},  // n=33
            {344.6f, base_form::codelet},  // n=34
            {200.9f, base_form::iterative_dif},  // n=35
            {159.0f, base_form::iterative_dif},  // n=36
            {381.4f, base_form::codelet},  // n=37
            {748.6f, base_form::codelet},  // n=38
            {277.4f, base_form::codelet},  // n=39
            {156.2f, base_form::iterative_dif},  // n=40
            {747.1f, base_form::codelet},  // n=41
            {372.6f, base_form::codelet},  // n=42
            {759.4f, base_form::codelet},  // n=43
            {223.0f, base_form::iterative_dif},  // n=44
            {264.6f, base_form::codelet},  // n=45
            {967.8f, base_form::codelet},  // n=46
            {2035.7f, base_form::codelet},  // n=47
            {203.1f, base_form::iterative_dif},  // n=48
            {239.4f, base_form::iterative_dif},  // n=49
            {348.2f, base_form::codelet},  // n=50
            {380.5f, base_form::codelet},  // n=51
            {286.5f, base_form::codelet},  // n=52
            {703.6f, base_form::codelet},  // n=53
            {380.9f, base_form::codelet},  // n=54
            {347.8f, base_form::iterative_dif},  // n=55
            {227.4f, base_form::iterative_dif},  // n=56
            {503.9f, base_form::codelet},  // n=57
            {680.1f, base_form::codelet},  // n=58
            {1422.5f, base_form::codelet},  // n=59
            {234.0f, base_form::iterative_dif},  // n=60
            {677.0f, base_form::codelet},  // n=61
            {1097.0f, base_form::codelet},  // n=62
            {332.9f, base_form::codelet},  // n=63
            {206.9f, base_form::iterative_dif}  // n=64
        }};
        return tab_v2_f32[n];
    }
    else if constexpr (sizeof(T) == 8 && xsimd::batch<T>::size == 2) {
        // v2 f64 W=2
        if (n == 120) return {756.1f, base_form::iterative_dif};  // catalog extra
        if (n > 64) return NO_ENTRY;
        constexpr std::array<base_cost_entry, 65> tab_v2_f64 = {{
            {-1.f, base_form::codelet},  // n=0 (unused)
            {-1.f, base_form::codelet},  // n=1
            {22.1f, base_form::codelet},  // n=2
            {21.5f, base_form::codelet},  // n=3
            {19.0f, base_form::codelet},  // n=4
            {22.8f, base_form::codelet},  // n=5
            {65.9f, base_form::iterative_dif},  // n=6
            {63.4f, base_form::codelet},  // n=7
            {23.1f, base_form::codelet},  // n=8
            {97.9f, base_form::iterative_dif},  // n=9
            {85.9f, base_form::iterative_dif},  // n=10
            {110.3f, base_form::codelet},  // n=11
            {93.3f, base_form::iterative_dif},  // n=12
            {254.9f, base_form::codelet},  // n=13
            {117.8f, base_form::codelet},  // n=14
            {137.3f, base_form::iterative_dif},  // n=15
            {99.5f, base_form::iterative_dif},  // n=16
            {274.8f, base_form::codelet},  // n=17
            {143.2f, base_form::codelet},  // n=18
            {292.5f, base_form::codelet},  // n=19
            {147.3f, base_form::iterative_dif},  // n=20
            {168.6f, base_form::iterative_dif},  // n=21
            {197.6f, base_form::iterative_dif},  // n=22
            {505.0f, base_form::codelet},  // n=23
            {145.9f, base_form::iterative_dif},  // n=24
            {203.7f, base_form::iterative_dif},  // n=25
            {269.6f, base_form::codelet},  // n=26
            {247.0f, base_form::iterative_dif},  // n=27
            {193.9f, base_form::iterative_dif},  // n=28
            {511.3f, base_form::codelet},  // n=29
            {234.4f, base_form::iterative_dif},  // n=30
            {587.7f, base_form::codelet},  // n=31
            {165.6f, base_form::iterative_dif},  // n=32
            {284.7f, base_form::iterative_dif},  // n=33
            {407.1f, base_form::codelet},  // n=34
            {273.0f, base_form::iterative_dif},  // n=35
            {243.4f, base_form::iterative_dif},  // n=36
            {782.0f, base_form::codelet},  // n=37
            {516.2f, base_form::codelet},  // n=38
            {796.9f, base_form::codelet},  // n=39
            {236.3f, base_form::iterative_dif},  // n=40
            {744.2f, base_form::codelet},  // n=41
            {324.7f, base_form::codelet},  // n=42
            {757.9f, base_form::codelet},  // n=43
            {342.8f, base_form::iterative_dif},  // n=44
            {342.7f, base_form::iterative_dif},  // n=45
            {637.8f, base_form::codelet},  // n=46
            {1429.7f, base_form::codelet},  // n=47
            {294.8f, base_form::iterative_dif},  // n=48
            {368.4f, base_form::iterative_dif},  // n=49
            {398.6f, base_form::iterative_dif},  // n=50
            {791.7f, base_form::codelet},  // n=51
            {1010.8f, base_form::codelet},  // n=52
            {2037.1f, base_form::codelet},  // n=53
            {401.6f, base_form::codelet},  // n=54
            {446.7f, base_form::iterative_dif},  // n=55
            {362.8f, base_form::iterative_dif},  // n=56
            {889.2f, base_form::codelet},  // n=57
            {744.4f, base_form::codelet},  // n=58
            {1607.0f, base_form::codelet},  // n=59
            {418.1f, base_form::iterative_dif},  // n=60
            {1160.4f, base_form::codelet},  // n=61
            {845.1f, base_form::codelet},  // n=62
            {508.0f, base_form::iterative_dif},  // n=63
            {334.0f, base_form::iterative_dif}  // n=64
        }};
        return tab_v2_f64[n];
    }
    return NO_ENTRY;
}

}  // namespace admiral::detail
