#pragma once

// GENERATED by tools/fit_cost_model.cpp. Do not edit by hand.
// Regenerate: cmake -DADM_FIT_COST_MODEL=ON, target admiral_cost_model.

#include <array>
#include <cstddef>
#include <cstdint>
#include <tuple>
#include <type_traits>
#include <utility>

#include <admiral/detail/build_id.hpp>
#include <admiral/detail/math.hpp>
#include "cxx_compat.hpp"

namespace admiral::detail {

enum class base_form : std::uint8_t { codelet, iterative_dif, good_thomas,
                                      four_step, four_step_batched, rader, bluestein };

struct base_cost_entry {
    float cyc;
    base_form form;
};

inline constexpr std::size_t BASE_MODEL_NMIN = 2;
inline constexpr std::size_t BASE_MODEL_NMAX = 512;

namespace base_model {

// Build constants: Wi lanes per batch, bytes per complex element, vec and waste in lanes.
template<typename T>
struct env {
    static constexpr std::size_t Wi = build_width<T>;
    static constexpr double W = double(Wi);
    static constexpr double bytes = 2.0 * double(sizeof(T));
    static constexpr double vec(std::size_t m) { return double((m + Wi - 1) / Wi); }
    static constexpr double waste(std::size_t m) { return (vec(m) * W - double(m)) / W; }
};

template<typename T>
[[nodiscard]] constexpr double chain_work(std::size_t n) {
    return admiral::detail::chain_work(n, env<T>::Wi, build_vector_regs);
}

// Appends the three features every form shares: log2(lanes), ln(bytes per element), clang flag.
template<typename T, std::size_t K>
[[nodiscard]] constexpr std::array<double, K + 3> with_tail(const std::array<double, K>& a) {
    std::array<double, K + 3> f{};
    for (std::size_t i = 0; i < K; ++i) f[i] = a[i];
    f[K]     = ct_log2(env<T>::W);
    f[K + 1] = ct_log2(env<T>::bytes) / ct_log2(2.7182818284590452354);
    f[K + 2] = build_compiler == "clang" ? 1.0 : 0.0;
    return f;
}

// One straight-line kernel of length n, priced on the measured leaf table.
struct codelet {
    static constexpr base_form tag = base_form::codelet;
    static constexpr double bias = 1.3585945271309894;
    static constexpr std::array<double, 9> w = {
        0.09012900452310776, 0.4623839845795388, 0.016749058074134262, 0.0, 0.0,
        0.05032943800346652, 0.0, 0.0, -0.09695976468665471,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 9> features(std::size_t n) {
        using e = env<T>;
        const auto [lpf, nfac] = lpf_nfac(n);
        return with_tail<T>(std::array<double, 6>{
            ct_log2(double(n)),
            ct_log2(leaf_cost_cyc<T>(n)),
            e::vec(n),
            e::waste(n),
            double(nfac),
            ct_log2(double(lpf)),
        });
    }
};

// The DIF pass chain, priced on chain_work: the cheapest radix path over n's divisors.
struct iterative_dif {
    static constexpr base_form tag = base_form::iterative_dif;
    static constexpr double bias = 2.88524763020275;
    static constexpr std::array<double, 9> w = {
        0.43820386866475536, 0.0, 0.0020535547130466195, 0.0, 0.22070383881087738, 0.0, 0.0,
        0.030732415702841888, 0.0,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 9> features(std::size_t n) {
        using e = env<T>;
        const auto [lpf, nfac] = lpf_nfac(n);
        const double cw = chain_work<T>(n);
        return with_tail<T>(std::array<double, 6>{
            ct_log2(double(n)),
            cw,
            cw * ct_log2(double(n)),
            double(nfac),
            ct_log2(double(lpf)),
            e::waste(lpf),
        });
    }
};

// The prime factor split at balanced_split(n), priced on both sub-transform lengths.
struct good_thomas {
    static constexpr base_form tag = base_form::good_thomas;
    static constexpr double bias = 2.983103271700825;
    static constexpr std::array<double, 13> w = {
        0.16284464352859548, 0.0, 0.0, 0.0, 0.0, 0.05706582467934254, 0.0, 0.0,
        0.06555959451265599, 0.09163401180507977, 0.0, 0.0, -0.07370091659046954,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 13> features(std::size_t n) {
        using e = env<T>;
        const auto [n1, n2] = balanced_split(n);
        return with_tail<T>(std::array<double, 10>{
            ct_log2(double(n)),
            e::vec(n1) * double(n2) / double(n1),
            double(n2) * e::vec(n1),
            double(n1) * e::vec(n2),
            ct_log2(double(n1)),
            ct_log2(double(n2)),
            e::waste(n1),
            e::waste(n2),
            double(n) / e::W,
            ct_log2(four_step_cost<T>(n1, n2)),
        });
    }
};

// The N = n1*n2 four-step split, priced on the two leaf lengths and the transpose.
struct four_step {
    static constexpr base_form tag = base_form::four_step;
    static constexpr double bias = 2.4400055528738553;
    static constexpr std::array<double, 13> w = {
        0.1356340890131949, 0.0, 0.0009572244499606585, 0.0, 0.0, 0.11338676096267923, 0.0, 0.0,
        0.0, 0.3799991043386408, 0.0, 0.0, -0.2290031124634066,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 13> features(std::size_t n) {
        using e = env<T>;
        const auto [n1, n2] = balanced_split(n);
        return with_tail<T>(std::array<double, 10>{
            ct_log2(double(n)),
            e::vec(n1) * double(n2) / double(n1),
            double(n2) * e::vec(n1),
            double(n1) * e::vec(n2),
            ct_log2(double(n1)),
            ct_log2(double(n2)),
            e::waste(n1),
            e::waste(n2),
            double(n) / e::W,
            ct_log2(four_step_cost<T>(n1, n2)),
        });
    }
};

// Prime n as a length-(n-1) cyclic convolution, priced on the DIF chain over n-1.
struct rader {
    static constexpr base_form tag = base_form::rader;
    static constexpr double bias = 3.692587978825538;
    static constexpr std::array<double, 12> w = {
        0.0, 0.6068274788441181, 0.0, 4.2423542361037304e-05, 0.0015035409836936472,
        0.04954426490770766, -0.06178900572675743, 0.06362342828377744, 0.9689598977298833,
        -0.042084007239494806, 0.0, -0.11231787275475227,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 12> features(std::size_t n) {
        using e = env<T>;
        const std::size_t L = n > 2 ? n - 1 : 1;
        const double cw = chain_work<T>(L);
        return with_tail<T>(std::array<double, 9>{
            ct_log2(double(n)),
            ct_log2(double(L)),
            cw,
            cw * ct_log2(double(L)),
            e::vec(L),
            e::waste(L),
            double(lpf_nfac(L)[1]),
            ct_log2(double(lpf_nfac(L)[0])),
            cw == 0.0 && L > 1 ? 1.0 : 0.0,
        });
    }
};

// Chirp convolution at the smooth pad from bluestein_choose_pad, priced on that pad.
struct bluestein {
    static constexpr base_form tag = base_form::bluestein;
    static constexpr double bias = 3.98253758795364;
    static constexpr std::array<double, 11> w = {
        0.5845518600309761, 0.0, 0.0, 0.005699361313442483, 0.0, 0.0, 0.0, 0.0,
        -0.1983077226320634, 0.22755954007287954, 0.0,
    };
    template<typename T>
    [[nodiscard]] static constexpr std::array<double, 11> features(std::size_t n) {
        using e = env<T>;
        const std::size_t m = bluestein_choose_pad(n);
        const double cw = chain_work<T>(m);
        return with_tail<T>(std::array<double, 8>{
            ct_log2(double(n)),
            ct_log2(double(m)),
            double(m) / double(n),
            cw,
            cw * ct_log2(double(m)),
            e::vec(m),
            e::waste(m),
            double(lpf_nfac(m)[1]),
        });
    }
};

using forms = std::tuple<codelet, iterative_dif, good_thomas, four_step, rader, bluestein>;
inline constexpr std::size_t NFORM = std::tuple_size_v<forms>;

// Predicted ln(cycles) for form M at length n: bias + w . features.
template<typename M, typename T>
[[nodiscard]] constexpr double score(std::size_t n) {
    const auto x = M::template features<T>(n);
    static_assert(std::tuple_size_v<admiral::detail::remove_cvref_t<decltype(x)>> ==
                  std::tuple_size_v<admiral::detail::remove_cvref_t<decltype(M::w)>>,
                  "feature/coefficient count mismatch");
    double acc = M::bias;
    for (std::size_t i = 0; i < x.size(); ++i) acc += M::w[i] * x[i];
    return acc;
}

template<typename T, std::size_t... I>
[[nodiscard]] constexpr auto score_all(std::size_t n, std::index_sequence<I...>) {
    return std::array<double, sizeof...(I)>{score<std::tuple_element_t<I, forms>, T>(n)...};
}

template<std::size_t... I>
[[nodiscard]] constexpr auto tags(std::index_sequence<I...>) {
    return std::array<base_form, sizeof...(I)>{std::tuple_element_t<I, forms>::tag...};
}

}

struct base_model_ranking {
    std::array<base_form, base_model::NFORM> form{};
    std::array<float, base_model::NFORM> log_cyc{};
    std::size_t count = 0;
    float best_cyc = -1.f;
};

[[nodiscard]] constexpr const char* base_form_name(base_form f) noexcept {
    switch (f) {
    case base_form::codelet:           return "codelet";
    case base_form::iterative_dif:     return "iterative_dif";
    case base_form::good_thomas:       return "good_thomas";
    case base_form::four_step:         return "four_step";
    case base_form::four_step_batched: return "four_step_batched";
    case base_form::rader:             return "rader";
    case base_form::bluestein:         return "bluestein";
    }
    return "?";
}

// Every form scored at n, cheapest first. best_cyc is exp() of the winner, so it is in cycles.
template<typename T>
[[nodiscard]] constexpr base_model_ranking score_ranking(std::size_t n) {
    using namespace base_model;
    base_model_ranking out;
    if (n < BASE_MODEL_NMIN || n > BASE_MODEL_NMAX) return out;

    constexpr auto seq = std::make_index_sequence<NFORM>{};
    const auto z = score_all<T>(n, seq);
    constexpr auto tag = tags(seq);

    std::array<bool, NFORM> used{};
    for (std::size_t k = 0; k < NFORM; ++k) {
        std::size_t bi = NFORM;
        for (std::size_t f = 0; f < NFORM; ++f)
            if (!used[f] && (bi == NFORM || z[f] < z[bi])) bi = f;
        used[bi] = true;
        out.form[k] = tag[bi];
        out.log_cyc[k] = float(z[bi]);
        if (k == 0) out.best_cyc = float(ct_exp(z[bi]));
    }
    out.count = NFORM;
    return out;
}

// score_ranking memoized for 2..512 in a function-local static table.
template<typename T>
[[nodiscard]] inline const base_model_ranking& base_route_ranking(std::size_t n) {
    static const std::array<base_model_ranking, BASE_MODEL_NMAX + 1> table = [] {
        std::array<base_model_ranking, BASE_MODEL_NMAX + 1> t{};
        for (std::size_t i = BASE_MODEL_NMIN; i <= BASE_MODEL_NMAX; ++i) t[i] = score_ranking<T>(i);
        return t;
    }();
    return table[n <= BASE_MODEL_NMAX ? n : 0];
}

// The cheapest form at n and its predicted cycles; cyc is -1 outside 2..512.
template<typename T>
[[nodiscard]] inline base_cost_entry base_cost_for(std::size_t n) noexcept {
    const auto& r = base_route_ranking<T>(n);
    if (r.count == 0) return {-1.f, base_form::codelet};
    return {r.best_cyc, r.form[0]};
}

}
