#pragma once

// ============================================================================
// Per-butterfly radix-IP DFT kernels (ADM_ALWAYS_INLINE, perf-critical) and the
// register/SIMD-width-derived unroll policy for the vectorized DIF a-loop.
//
// Performance-critical: any change must be bench-gated. Generated by
// if constexpr / poet::static_for, not hand-unrolled.
// ============================================================================

#include <cstddef>
#include <type_traits>
#include <utility>

#include <poet/poet.hpp>

#include "ct_math.hpp"  // ct_sincos_turns, ct_sincos_t

// ADM_ALWAYS_INLINE / ADM_RESTRICT for the butterfly helpers below (paired with
// the #include "undef_macros.hpp" at the end of this header).
#include "macros.hpp"

namespace admiral {
namespace detail {

// ----------------------------------------------------------------------------
// Symmetric (Singleton) radix-IP DFT for ODD IP, generated at compile time.
//
// The naive DFT matrix costs ~IP^2 complex MACs. On Alder Lake the radix-5/7 DIF
// passes are bound by the FMA port (p01), NOT by stack spills (the held inputs
// spill at cpi-0.5 onto otherwise-idle store ports). Cross-checked with simdref
// + llvm-mca: the lever is fewer multiplies, not fewer spills.
//
// This routine exploits the conjugate symmetry W_IP^{(IP-m)k} = conj(W_IP^{mk}):
// pairing input j with IP-j lets each output reuse the pair sum a_m = x_m+x_{IP-m}
// and difference d_m = x_m-x_{IP-m}, halving the real multiplies. For a W=4 block
// this drops radix-5 RThroughput 35.8->24.3 and radix-7 79.3->44.2 (llvm-mca,
// alderlake) — and it is fully generic in IP (no per-radix hand-derivation).
//
//   out_0      = x_0 + sum_m a_m
//   PR = x0r + sum_m cos(2pi mk/IP) ar_m,  PI = x0i + sum_m cos(2pi mk/IP) ai_m
//   QR =       sum_m sin(2pi mk/IP) di_m,  QI =       sum_m sin(2pi mk/IP) dr_m
//   forward:  out_k = (PR+QR, PI-QI),  out_{IP-k} = (PR-QR, PI+QI)
//   inverse:  the sin terms flip sign (conjugate twiddle), i.e. swap the +/-.
//
// V is xsimd::batch<T> (vectorized body) or T (scalar tail). emit is invoked as
// emit(std::integral_constant<int,k>{}, yr, yi) the moment each un-twiddled
// output is ready, so the caller applies the output twiddle and stores it while
// only x0 + the pair sums/diffs stay live. ADM_ALWAYS_INLINE: the win is the
// reduced op count landing in the pass loop, not an out-of-line call.
// ----------------------------------------------------------------------------
template<typename T, bool Forward, int IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void radix_sym_dft(const V (&xr)[static_cast<std::size_t>(IP)],
                                     const V (&xi)[static_cast<std::size_t>(IP)],
                                     Emit&& emit) {
    static_assert(IP % 2 == 1 && IP >= 3, "symmetric DFT is for odd radix >= 3");
    constexpr int H = (IP - 1) / 2;
    constexpr std::size_t HA = static_cast<std::size_t>(H) + 1;  // array bound (avoid sign-conv)
    V ar[HA], ai[HA], dr[HA], di[HA];
    poet::static_for<1, H + 1>([&](auto M) {
        constexpr std::size_t m = M;
        constexpr std::size_t mc = static_cast<std::size_t>(IP) - m;  // conjugate index
        ar[m] = xr[m] + xr[mc];
        ai[m] = xi[m] + xi[mc];
        dr[m] = xr[m] - xr[mc];
        di[m] = xi[m] - xi[mc];
    });
    {
        V sr = xr[0], si = xi[0];
        poet::static_for<1, H + 1>([&](auto M) {
            constexpr std::size_t m = M;
            sr = sr + ar[m];
            si = si + ai[m];
        });
        emit(std::integral_constant<int, 0>{}, sr, si);
    }
    poet::static_for<1, H + 1>([&](auto K) {
        constexpr int k = K.value;
        V PR = xr[0], PI = xi[0], QR = V(T(0)), QI = V(T(0));
        poet::static_for<1, H + 1>([&](auto M) {
            constexpr std::size_t m = M;
            constexpr ct_sincos_t w = ct_sincos_turns(
                static_cast<long long>((static_cast<int>(m) * k) % IP), static_cast<long long>(IP));
            PR = PR + V(static_cast<T>(w.c)) * ar[m];
            PI = PI + V(static_cast<T>(w.c)) * ai[m];
            QR = QR + V(static_cast<T>(w.s)) * di[m];
            QI = QI + V(static_cast<T>(w.s)) * dr[m];
        });
        if constexpr (Forward) {
            emit(std::integral_constant<int, k>{}, PR + QR, PI - QI);
            emit(std::integral_constant<int, IP - k>{}, PR - QR, PI + QI);
        } else {
            emit(std::integral_constant<int, k>{}, PR - QR, PI + QI);
            emit(std::integral_constant<int, IP - k>{}, PR + QR, PI - QI);
        }
    });
}

// ----------------------------------------------------------------------------
// Per-stage DIF twiddle W_IP^{±N} applied to one register-resident (re,im) pair,
// with compile-time elision of every trivial rotation. The split-radix kernel
// below feeds N = 0..IP/2-1 and the recursion's parent radix as IP; this helper
// is what keeps the multiply count at the hand-written optimum:
//
//   axis     (W = 1, -1, ±i)        -> 0 multiplies (sign flip / re-im swap)
//   diagonal (|cos| = |sin| = 1/√2) -> 2 multiplies (factor the common 1/√2)
//   general                         -> 4 multiplies (full complex rotation)
//
// W = c + i·s with c = cos θ, s = sin θ, θ = 2π·(±N)/IP. Multiplying (fr + i·fi):
//   rr = c·fr - s·fi,  ri = c·fi + s·fr.
// ct_sincos_turns range-reduces on integer octants and sets the axis/diagonal
// values to EXACT 0 / ±1 / ±(√2/2), so the exact-equality if constexpr guards
// below are safe and fire for every W_4 / W_8 stage twiddle (the only ones the
// bench-gated radix-4 and radix-8 paths use). For radix ≥ 16 the residual
// (non-axis, non-diagonal) rotations fall through to the plain general form,
// which the compiler contracts to FMAs (matching radix_sym_dft's idiom) and is
// V-generic across batch<T> and the scalar tail.
// ----------------------------------------------------------------------------
template<typename T, bool Forward, int IP, int N, typename V>
[[nodiscard]] ADM_ALWAYS_INLINE std::pair<V, V> apply_stage_twiddle(V fr, V fi) {
    constexpr long long sign = Forward ? -1LL : 1LL;
    constexpr ct_sincos_t w =
        ct_sincos_turns(sign * static_cast<long long>(N), static_cast<long long>(IP));
    if constexpr (w.s == 0.0 && w.c == 1.0) {
        return {fr, fi};                                  // W^0 = 1
    } else if constexpr (w.s == 0.0 && w.c == -1.0) {
        return {-fr, -fi};                                // -1
    } else if constexpr (w.c == 0.0 && w.s == -1.0) {
        return {fi, -fr};                                 // -i  (forward W_IP^{IP/4})
    } else if constexpr (w.c == 0.0 && w.s == 1.0) {
        return {-fi, fr};                                 // +i
    } else if constexpr (w.c == w.s) {
        // Diagonal, s/c = +1: rr = c(fr - fi), ri = c(fi + fr). One mult each.
        const V c(static_cast<T>(w.c));
        return {c * (fr - fi), c * (fi + fr)};
    } else if constexpr (w.c == -w.s) {
        // Diagonal, s/c = -1: rr = c(fr + fi), ri = c(fi - fr). One mult each.
        const V c(static_cast<T>(w.c));
        return {c * (fr + fi), c * (fi - fr)};
    } else {
        // General rotation; plain arithmetic contracts to FMAs (ffp-contract).
        const V c(static_cast<T>(w.c)), s(static_cast<T>(w.s));
        return {c * fr - s * fi, c * fi + s * fr};
    }
}

// Generic recursive split-radix DIF butterfly for any power-of-two radix IP. The
// radix-2 base case is a pure sum/diff (zero mults); each larger radix splits Cooley-Tukey
// decimation-in-frequency into an even half (sums -> DFT_{IP/2} -> outputs 2k) and
// an odd half (diffs, stage-twiddled by W_IP^n -> DFT_{IP/2} -> outputs 2k+1).
//
// The two halves live in SEPARATE scopes (mirroring radix8_dft's two {} blocks) so
// the even-half temporaries are dead before the odd half allocates its own — peak
// live batches stay bounded by poet::vector_register_count() (16 YMM on AVX2),
// the same ceiling the hand kernels were tuned to, with no spills. The emit-index
// remap (2k even, 2k+1 odd) is compile-time, yielding emission order
// {0,4,2,6,1,5,3,7} for IP=8 — same order and term-for-term arithmetic as the old
// radix8_dft (A/B: within ±2% cycles, identical vmulpd/FMA counts). All trivial
// twiddles fold away in apply_stage_twiddle (0 mults for radix-4, 4 for radix-8).
template<typename T, bool Forward, int IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void pow2_dif_butterfly(const V (&xr)[static_cast<std::size_t>(IP)],
                                          const V (&xi)[static_cast<std::size_t>(IP)],
                                          Emit&& emit) {
    static_assert(IP >= 2 && (IP & (IP - 1)) == 0, "pow2_dif_butterfly: IP must be a power of two >= 2");
    if constexpr (IP == 2) {
        emit(std::integral_constant<int, 0>{}, xr[0] + xr[1], xi[0] + xi[1]);
        emit(std::integral_constant<int, 1>{}, xr[0] - xr[1], xi[0] - xi[1]);
    } else {
        constexpr int H = IP / 2;
        constexpr std::size_t HU = static_cast<std::size_t>(H);
        {   // Even half: e_n = x_n + x_{n+H}; DFT_H(e) -> outputs 2k.
            V er[HU], ei[HU];
            poet::static_for<0, H>([&](auto Nc) {
                constexpr std::size_t n = Nc;
                er[n] = xr[n] + xr[n + HU];
                ei[n] = xi[n] + xi[n + HU];
            });
            pow2_dif_butterfly<T, Forward, H, V>(er, ei, [&](auto Kc, V yr, V yi) {
                emit(std::integral_constant<int, 2 * decltype(Kc)::value>{}, yr, yi);
            });
        }
        {   // Odd half: f_n = (x_n - x_{n+H})·W_IP^n; DFT_H(f) -> outputs 2k+1.
            V fr[HU], fi[HU];
            poet::static_for<0, H>([&](auto Nc) {
                constexpr int n = Nc.value;
                constexpr std::size_t nu = static_cast<std::size_t>(n);
                auto [tr, ti] = apply_stage_twiddle<T, Forward, IP, n, V>(
                    xr[nu] - xr[nu + HU], xi[nu] - xi[nu + HU]);
                fr[nu] = tr;
                fi[nu] = ti;
            });
            pow2_dif_butterfly<T, Forward, H, V>(fr, fi, [&](auto Kc, V yr, V yi) {
                emit(std::integral_constant<int, 2 * decltype(Kc)::value + 1>{}, yr, yi);
            });
        }
    }
}

// Restage admission: the two-sweep restage in dif_passes.hpp fires when the
// radix's input set alone (2*IP batches) cannot fit the register file with
// headroom for the split kernel's temporaries — the pass runs its even and odd
// half-butterflies as two physical sweeps, reloading inputs per sweep (9dcdda5;
// a butterfly-level single-loop reload variant was CSE'd back to spilling
// codegen, so the split lives at the pass level). At 32 regs this is IP >= 16
// for f64 W=8 (2*16 = 32) and IP >= 32 for f32 W=16; narrow-register ISAs
// never admit 16/32 radices at all.
template<int IP>
inline constexpr bool dif_butterfly_wants_reload =
    (IP & (IP - 1)) == 0 && IP >= 4 &&
    2u * static_cast<unsigned>(IP) >= poet::vector_register_count();

// Unified per-butterfly radix-IP DFT used by all DIF pass variants. Routes odd
// IP (3,5,7,...) through the low-multiply symmetric kernel, power-of-two IP>=4
// through the generic split-radix kernel (radix-4/8/16/32/... uniformly), and
// the remaining even IP (2,6) through
// the naive DFT matrix (cheap; W folds to +-1/+-i adds for these radices). emit is
// invoked emit(integral_constant<int,k>, yr, yi) per un-twiddled output k; the
// caller applies the output twiddle and stores. V = batch<T> or T (scalar tail).
template<typename T, bool Forward, int IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void dif_butterfly(const V (&tr)[static_cast<std::size_t>(IP)],
                                     const V (&ti)[static_cast<std::size_t>(IP)],
                                     Emit&& emit) {
    if constexpr (IP % 2 == 1 && IP >= 3) {
        radix_sym_dft<T, Forward, IP>(tr, ti, std::forward<Emit>(emit));
    } else if constexpr (IP >= 4 && (IP & (IP - 1)) == 0) {
        pow2_dif_butterfly<T, Forward, IP>(tr, ti, std::forward<Emit>(emit));
    } else {
        poet::static_for<0, IP>([&](auto K) {
            constexpr int k = K.value;
            V sr = tr[0], si = ti[0];
            poet::static_for<1, IP>([&](auto J) {
                constexpr int jj = J.value;
                constexpr ct_sincos_t w = ct_sincos_turns(
                    (Forward ? -1 : 1) * static_cast<long long>(jj) * static_cast<long long>(k),
                    static_cast<long long>(IP));
                sr = sr + V(static_cast<T>(w.c)) * tr[static_cast<std::size_t>(jj)]
                        - V(static_cast<T>(w.s)) * ti[static_cast<std::size_t>(jj)];
                si = si + V(static_cast<T>(w.c)) * ti[static_cast<std::size_t>(jj)]
                        + V(static_cast<T>(w.s)) * tr[static_cast<std::size_t>(jj)];
            });
            emit(std::integral_constant<int, k>{}, sr, si);
        });
    }
}

// ----------------------------------------------------------------------------
// Register/SIMD-width-derived unroll factor for the vectorized DIF a-loop.
//
// Processing U independent W-wide butterflies per iteration multiplies the live
// batch working set by U, so U is capped to keep that set inside the
// architectural vector register file. poet::vector_register_count() is the
// consteval register count for the active ISA (16 YMM on AVX2, 32 ZMM on
// AVX-512). The radix-IP butterfly holds ~2*IP+6 batches live at its peak (the
// symmetric kernel: x0 + 4*(IP-1)/2 pair sums/diffs + 4 accumulators; matches
// measured radix-5=16, radix-7=20), so U = registers / peak_live.
//
// peak_live = 2*IP + 10 is an empirically calibrated upper bound on the live
// batch set (the symmetric kernel holds x0, the 4*(IP-1)/2 pair sums/diffs, the
// 4 accumulators, plus twiddle/output temps; calibrated against measured codegen
// so the chosen U produces NO vector spills on either ISA -- a smaller constant
// made radix-5 spill at U=2 on AVX-512).
//
// Result: U=1 for every radix on AVX2 (16 regs) -- which is also the throughput
// optimum there: simdref/llvm-mca show the radix-5/7 a-loops are dispatch- and
// FMA-port-bound at U=1, so the out-of-order window already overlaps butterflies
// across iterations and a larger U would only add spills.
// On AVX-512 (32 regs) the register-heavy radix-5/7 stay at U=1 (no spill, matching
// the measured W=8 zero-spill point); only the cheap small radices gain U=2.
template<int IP>
consteval std::size_t dif_pass_unroll() {
    constexpr std::size_t peak_live = 2u * static_cast<std::size_t>(IP) + 10u;
    constexpr std::size_t budget = poet::vector_register_count();
    constexpr std::size_t u = budget / peak_live;
    return u < 1u ? 1u : u;
}

} // namespace detail
} // namespace admiral

#include "undef_macros.hpp"

