#pragma once

// ============================================================================
// Per-butterfly radix-IP DFT kernels (ADM_ALWAYS_INLINE, perf-critical) and
// unroll policy for the vectorized DIF a-loop.
//
// DIRECTION-FREE. Every kernel computes the FORWARD DFT only; the inverse rides
// the same code in swapped domain (the caller exchanges re/im planes at the AoS
// boundaries), because swap(fwd(swap x)) == conj(fwd(conj x)) == inv(x). Two
// consequences the kernels rely on: multiplying a swapped pair by w is a
// multiply by conj(w), so the stage twiddle self-conjugates and tables need no
// direction; and the +/- slot assignment in radix_sym_dft is the conjugate flip
// the swap performs. `Forward` survives only on boundary passes.
//
// Generated by if constexpr / poet::static_for, not hand-unrolled.
// Any change must be bench-gated.
// ============================================================================

#include <bit>
#include <cstddef>
#include <type_traits>
#include <utility>

#include <poet/poet.hpp>

#include "ct_math.hpp"  // ct_sincos_turns, ct_sincos_t, coprime_split

// ADM_ALWAYS_INLINE / ADM_RESTRICT for the butterfly helpers below (paired with
// the #include "undef_macros.hpp" at the end of this header).
#include "macros.hpp"

namespace admiral {
namespace detail {

// ----------------------------------------------------------------------------
// Symmetric (Singleton) radix-IP DFT for ODD IP. Conjugate symmetry
// W_IP^{(IP-m)k} = conj(W_IP^{mk}) pairs input j with IP-j, halving real
// multiplies via the sum/difference split:
//
//   out_0 = x_0 + sum_m a_m
//   PR = x0r + sum_m cos(2pi mk/IP) ar_m,  PI = x0i + sum_m cos(2pi mk/IP) ai_m
//   QR =       sum_m sin(2pi mk/IP) di_m,  QI =       sum_m sin(2pi mk/IP) dr_m
//   out_k = (PR+QR, PI-QI),  out_{IP-k} = (PR-QR, PI+QI)
//
// These passes are FMA-port bound, so never trade the halved multiply count
// back for a direct form with fewer temporaries. V-generic (batch or scalar).
// emit(integral_constant<size_t,k>{}, yr, yi) fires per output while only x0 +
// pair sums/diffs stay live.
// ----------------------------------------------------------------------------
template<typename T, std::size_t IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void radix_sym_dft(const V (&xr)[IP],
                                     const V (&xi)[IP],
                                     Emit&& emit) {
    static_assert(IP % 2 == 1 && IP >= 3, "symmetric DFT is for odd radix >= 3");
    constexpr std::size_t H = (IP - 1) / 2;
    constexpr std::size_t HA = H + 1;
    V ar[HA], ai[HA], dr[HA], di[HA];
    poet::static_for<1, H + 1>([&](const auto m) {
        constexpr std::size_t mc = IP - m;  // conjugate index
        ar[m] = xr[m] + xr[mc];
        ai[m] = xi[m] + xi[mc];
        dr[m] = xr[m] - xr[mc];
        di[m] = xi[m] - xi[mc];
    });
    {
        V sr = xr[0], si = xi[0];
        poet::static_for<1, H + 1>([&](const auto m) {
            sr = sr + ar[m];
            si = si + ai[m];
        });
        emit(std::integral_constant<std::size_t, 0>{}, sr, si);
    }
    poet::static_for<1, H + 1>([&](const auto k) {
        V PR = xr[0], PI = xi[0], QR = V(T(0)), QI = V(T(0));
        poet::static_for<1, H + 1>([&](const auto m) {
            constexpr ct_sincos_t w = ct_sincos_turns(/*conjugate=*/false, (m * k) % IP, IP);
            PR = PR + V(static_cast<T>(w.c)) * ar[m];
            PI = PI + V(static_cast<T>(w.c)) * ai[m];
            QR = QR + V(static_cast<T>(w.s)) * di[m];
            QI = QI + V(static_cast<T>(w.s)) * dr[m];
        });
        emit(std::integral_constant<std::size_t, k>{}, PR + QR, PI - QI);
        emit(std::integral_constant<std::size_t, IP - k>{}, PR - QR, PI + QI);
    });
}

// ----------------------------------------------------------------------------
// Good-Thomas (prime-factor) butterfly for IP = N1*N2 with gcd(N1,N2) == 1.
// Generic in the factor pair: odd IP (15 = 5*3, two symmetric sub-DFTs) and even
// IP (10 = 5*2, 20 = 5*4, sub_dft routes the pow2 factor to pow2_dif_butterfly).
// radix_sym_dft is O(H^2) in H=(IP-1)/2, so a composite odd radix pays a naive
// DFT; the twiddle-free PFA cuts both the op count and the peak live set.
//
//   in  (Ruritanian): x[n1][n2] = t[(n1*N2 + n2*N1) % IP]
//   out (CRT):        emit at the k with k%N1==k1 and k%N2==k2
//
// The CRT index is a constexpr search, not a modular inverse, which is one less identity
// to keep right. K1/K2 are template parameters so the search runs inside the emit
// lambda (lambda parameters are not constant expressions in a nested lambda).
// ----------------------------------------------------------------------------
template<std::size_t N1, std::size_t N2, std::size_t K1, std::size_t K2>
inline constexpr std::size_t crt_index = [] {
    for (std::size_t k = 0; k < N1 * N2; ++k)
        if (k % N1 == K1 && k % N2 == K2) return k;
    return N1 * N2;
}();

template<typename T, std::size_t IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void pow2_dif_butterfly(const V (&xr)[IP], const V (&xi)[IP], Emit&& emit);

// Sub-DFT for one PFA stage. An EVEN composite radix splits coprime into a power
// of two and an odd part (10 = 2*5, 20 = 4*5), so one stage is not the symmetric
// kernel. Both forms emit natural k, which is all the CRT map below assumes.
template<typename T, std::size_t N, typename V, typename Emit>
ADM_ALWAYS_INLINE void sub_dft(const V (&xr)[N], const V (&xi)[N], Emit&& emit) {
    if constexpr (std::has_single_bit(N))
        pow2_dif_butterfly<T, N, V>(xr, xi, std::forward<Emit>(emit));
    else
        radix_sym_dft<T, N>(xr, xi, std::forward<Emit>(emit));
}

template<typename T, std::size_t N1, std::size_t N2, typename V, typename Emit>
ADM_ALWAYS_INLINE void pfa_dif_butterfly(const V (&tr)[N1 * N2],
                                         const V (&ti)[N1 * N2],
                                         Emit&& emit) {
    constexpr std::size_t IP = N1 * N2;
    static_assert(std::gcd(N1, N2) == 1, "PFA requires coprime factors");

    // Stage A: N2 independent DFT-N1 down the Ruritanian map, held as [k1][n2].
    V ar[N1][N2], ai[N1][N2];
    poet::static_for<0, N2>([&](const auto n2) {
        V br[N1], bi[N1];
        poet::static_for<0, N1>([&](const auto n1) {
            constexpr std::size_t src = (n1 * N2 + n2 * N1) % IP;
            br[n1] = tr[src];
            bi[n1] = ti[src];
        });
        sub_dft<T, N1>(br, bi, [&](auto K1, V yr, V yi) {
            ar[K1][n2] = yr;
            ai[K1][n2] = yi;
        });
    });

    // Stage B: N1 independent DFT-N2 across n2, emitted straight at the CRT index.
    // ar[k1]/ai[k1] are contiguous V[N2] rows, so they feed sub_dft directly.
    // coprime_split puts the *larger* factor in N1: that keeps this emit-carrying
    // body under clang's inline threshold.
    poet::static_for<0, N1>([&](const auto k1) {
        sub_dft<T, N2>(ar[k1], ai[k1], [&](const auto k2, V yr, V yi) {
            constexpr auto out = crt_index<N1, N2, k1, k2>;
            static_assert(out < IP, "CRT index must exist for coprime N1,N2");
            emit(std::integral_constant<std::size_t, out>{}, yr, yi);
        });
    });
}


// Flop count of radix_sym_dft: (IP-1)/2 pair sums/diffs (4 each) plus H outputs
// of 4 FMAs over H terms, i.e. 4H^2+10H. Quadratic, so a large odd radix pays a
// naive DFT even after the conjugate-symmetry halving.
[[nodiscard]] constexpr std::size_t sym_dft_ops(std::size_t n) noexcept {
    const std::size_t h = (n - 1) / 2;
    return 4 * h * h + 10 * h;
}

// Flop count of ct_dif_butterfly<N1,N2>: the two sub-DFT stages plus one general
// complex rotation (6 ops) per non-trivial stage twiddle. r*n2 < N1*N2 for every
// (r,n2), so the twiddle is trivial exactly when either index is zero.
[[nodiscard]] constexpr std::size_t ct_dft_ops(std::size_t n1, std::size_t n2) noexcept {
    return n2 * sym_dft_ops(n1) + n1 * sym_dft_ops(n2) + 6 * (n1 - 1) * (n2 - 1);
}

// Cooley-Tukey factor pair for an odd radix with NO coprime split, an odd
// prime power where the twiddle-free PFA does not apply. Taken only when the
// split's flop count beats the flat symmetric kernel. Smallest factor first, so
// stage B (which carries the emit) runs the fewer, larger sub-DFTs.
//
// Cost comparison (not a threshold) keeps 9 flat; 25, 27, 49 take the split.
[[nodiscard]] constexpr std::pair<std::size_t, std::size_t> odd_ct_split(std::size_t n) noexcept {
    if (n % 2 == 0 || coprime_split(n).first != 0) return {0, 0};
    for (std::size_t p = 3; p * p <= n; p += 2)
        if (n % p == 0 && ct_dft_ops(p, n / p) < sym_dft_ops(n)) return {p, n / p};
    return {0, 0};
}

// ----------------------------------------------------------------------------
// Stage twiddle W_IP^{±N} applied to one register-resident (re,im) pair, with
// compile-time elision of trivial rotations:
//
//   axis     (W = 1,-1,±i)          -> 0 multiplies (sign flip / re-im swap)
//   diagonal (|cos|=|sin|=1/√2)     -> 2 multiplies (factor 1/√2)
//   general                         -> 4 multiplies (full complex rotation)
//
// W = c+i·s, c=cos θ, s=sin θ, θ=2π(±N)/IP. Multiply (fr+i·fi):
//   rr = c·fr - s·fi,  ri = c·fi + s·fr.
// ct_sincos_turns reduces on integer octants; axis/diagonal values are EXACT
// 0/±1/±(√2/2), so if constexpr guards are safe and fire for every W_4/W_8
// stage twiddle. Radix>=16 residuals fall to the general form (compiler
// contracts to FMAs). V-generic: batch<T> and scalar tail.
// ----------------------------------------------------------------------------
template<typename T, std::size_t IP, std::size_t N, typename V>
[[nodiscard]] ADM_ALWAYS_INLINE std::pair<V, V> apply_stage_twiddle(V fr, V fi) {
    constexpr ct_sincos_t w = ct_sincos_turns(/*conjugate=*/true, N, IP);
    if constexpr (w.s == 0.0 && w.c == 1.0) {
        return {fr, fi};                                  // W^0 = 1
    } else if constexpr (w.s == 0.0 && w.c == -1.0) {
        return {-fr, -fi};                                // -1
    } else if constexpr (w.c == 0.0 && w.s == -1.0) {
        return {fi, -fr};                                 // -i  (forward W_IP^{IP/4})
    } else if constexpr (w.c == 0.0 && w.s == 1.0) {
        return {-fi, fr};                                 // +i
    } else if constexpr (w.c == w.s) {
        // Diagonal, s/c = +1: rr = c(fr - fi), ri = c(fi + fr). One mult each.
        const V c(static_cast<T>(w.c));
        return {c * (fr - fi), c * (fi + fr)};
    } else if constexpr (w.c == -w.s) {
        // Diagonal, s/c = -1: rr = c(fr + fi), ri = c(fi - fr). One mult each.
        const V c(static_cast<T>(w.c));
        return {c * (fr + fi), c * (fi - fr)};
    } else {
        // General rotation; plain arithmetic contracts to FMAs (ffp-contract).
        const V c(static_cast<T>(w.c)), s(static_cast<T>(w.s));
        return {c * fr - s * fi, c * fi + s * fr};
    }
}

// Generic recursive radix-2 DIF butterfly for any power-of-two radix IP.
// Radix-2 base: pure sum/diff (zero mults). Larger IP: even half (sums ->
// DFT_{IP/2} -> outputs 2k) and odd half (diffs, stage-twiddled by W_IP^n ->
// DFT_{IP/2} -> outputs 2k+1). Cooley-Tukey DIF, not split-radix: both
// sub-problems are DFT_{IP/2}, never DFT_{IP/4}.
// Two halves in SEPARATE scopes: even-half temporaries die before the odd half
// allocates, bounding peak live batches to the register file with no spills.
template<typename T, std::size_t IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void pow2_dif_butterfly(const V (&xr)[IP],
                                          const V (&xi)[IP],
                                          Emit&& emit) {
    static_assert(IP >= 2 && std::has_single_bit(IP), "pow2_dif_butterfly: IP must be a power of two >= 2");
    if constexpr (IP == 2) {
        emit(std::integral_constant<std::size_t, 0>{}, xr[0] + xr[1], xi[0] + xi[1]);
        emit(std::integral_constant<std::size_t, 1>{}, xr[0] - xr[1], xi[0] - xi[1]);
    } else {
        constexpr std::size_t H = IP / 2;
        {   // Even half: e_n = x_n + x_{n+H}; DFT_H(e) -> outputs 2k.
            V er[H], ei[H];
            poet::static_for<0, H>([&](const auto n) {
                er[n] = xr[n] + xr[n + H];
                ei[n] = xi[n] + xi[n + H];
            });
            pow2_dif_butterfly<T, H, V>(er, ei, [&](auto Kc, V yr, V yi) {
                emit(std::integral_constant<std::size_t, 2 * Kc>{}, yr, yi);
            });
        }
        {   // Odd half: f_n = (x_n - x_{n+H})·W_IP^n; DFT_H(f) -> outputs 2k+1.
            V fr[H], fi[H];
            poet::static_for<0, H>([&](const auto n) {
                auto [tr, ti] = apply_stage_twiddle<T, IP, n, V>(
                    xr[n] - xr[n + H], xi[n] - xi[n + H]);
                fr[n] = tr;
                fi[n] = ti;
            });
            pow2_dif_butterfly<T, H, V>(fr, fi, [&](auto Kc, V yr, V yi) {
                emit(std::integral_constant<std::size_t, 2 * Kc + 1>{}, yr, yi);
            });
        }
    }
}

// ----------------------------------------------------------------------------
// Cooley-Tukey DIF split of an ODD composite radix IP = N1*N2 that has no
// coprime factorization. Same decimation as pow2_dif_butterfly (which is this
// with N1 == 2), but both sub-DFTs are the symmetric kernel and a twiddle stage
// sits between them:
//
//   n = n1*N2 + n2,  k = k2*N1 + r
//   X[k2*N1+r] = sum_{n2} W_N2^{n2 k2} [ W_IP^{n2 r} sum_{n1} x[n1 N2+n2] W_N1^{n1 r} ]
//
// It pays IP - N1 - N2 + 1 rotations against the flat kernel's O(IP^2), and the
// stage-A scope dies before stage B allocates, so peak live drops with it.
// odd_ct_split does the comparison.
// ----------------------------------------------------------------------------
template<typename T, std::size_t N1, std::size_t N2, typename V, typename Emit>
ADM_ALWAYS_INLINE void ct_dif_butterfly(const V (&tr)[N1 * N2],
                                        const V (&ti)[N1 * N2],
                                        Emit&& emit) {
    constexpr std::size_t IP = N1 * N2;
    static_assert(N1 % 2 == 1 && N2 % 2 == 1 && N1 >= 3 && N2 >= 3,
                  "ct_dif_butterfly: both factors must be odd radices >= 3");

    // Stage A: N2 independent DFT-N1 over the n1 stride, stage-twiddled in place.
    V ar[N1][N2], ai[N1][N2];
    poet::static_for<0, N2>([&](const auto n2) {
        V br[N1], bi[N1];
        poet::static_for<0, N1>([&](const auto n1) {
            br[n1] = tr[n1 * N2 + n2];
            bi[n1] = ti[n1 * N2 + n2];
        });
        radix_sym_dft<T, N1>(br, bi, [&](const auto r, V yr, V yi) {
            constexpr std::size_t e = static_cast<std::size_t>(decltype(r)::value)
                                    * static_cast<std::size_t>(decltype(n2)::value);
            const auto [fr, fi] = apply_stage_twiddle<T, IP, e, V>(yr, yi);
            ar[r][n2] = fr;
            ai[r][n2] = fi;
        });
    });

    // Stage B: N1 independent DFT-N2 across n2, emitted at k = k2*N1 + r.
    poet::static_for<0, N1>([&](const auto r) {
        radix_sym_dft<T, N2>(ar[r], ai[r], [&](const auto k2, V yr, V yi) {
            emit(std::integral_constant<std::size_t, k2 * N1 + r>{}, yr, yi);
        });
    });
}

// Restage admission: the two-sweep restage (dif_passes.hpp) fires when 2*IP
// batches do not fit the register file with headroom. The pass then runs the even
// and odd half-butterflies as two physical sweeps. The reload must happen at pass
// level, not inside one butterfly loop: there the compiler CSEs it away and
// spills again. Narrow-register ISAs never admit radix 16 or 32.
template<std::size_t IP>
inline constexpr bool dif_butterfly_wants_reload =
    butterfly_wants_reload(IP, poet::vector_register_count());

// Unified per-butterfly radix-IP DFT for all DIF pass variants. Routes:
//   odd prime power (25)  -> ct_dif_butterfly (odd Cooley-Tukey split)
//   odd IP (3,5,7,9,...)  -> radix_sym_dft (symmetric kernel)
//   pow2 IP >= 4          -> pow2_dif_butterfly (recursive Cooley-Tukey DIF)
//   even IP (2,6)         -> naive DFT matrix (W folds to +-1/+-i adds)
// emit(integral_constant<size_t,k>, yr, yi) per un-twiddled output k, NOT in
// ascending k, since pow2_dif_butterfly permutes.
// V = batch<T> or T (scalar tail).
template<typename T, std::size_t IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void dif_butterfly(const V (&tr)[IP],
                                     const V (&ti)[IP],
                                     Emit&& emit) {
    constexpr auto ct = odd_ct_split(IP);
    // Even composite radix (10 = 5*2, 20 = 5*4): coprime, so the twiddle-free PFA
    // applies and costs N2*sym(N1) + N1*pow2(N2) against the flat kernel's O(IP^2).
    // Odd IP is excluded on purpose: an odd coprime radix keeps the flat kernel
    // in a middle pass and takes the PFA only at the terminal (dif_butterfly_terminal),
    // and that split is deliberate; this branch must not silently re-route it.
    constexpr auto pf = coprime_split(IP);
    if constexpr (ct.first != 0) {
        ct_dif_butterfly<T, ct.first, ct.second>(tr, ti, std::forward<Emit>(emit));
    } else if constexpr (IP % 2 == 1 && IP >= 3) {
        radix_sym_dft<T, IP>(tr, ti, std::forward<Emit>(emit));
    } else if constexpr (IP % 2 == 0 && pf.first != 0) {
        pfa_dif_butterfly<T, pf.first, pf.second>(tr, ti, std::forward<Emit>(emit));
    } else if constexpr (IP >= 4 && std::has_single_bit(IP)) {
        pow2_dif_butterfly<T, IP>(tr, ti, std::forward<Emit>(emit));
    } else {
        poet::static_for<0, IP>([&](const auto k) {
            V sr = tr[0], si = ti[0];
            poet::static_for<1, IP>([&](const auto jj) {
                constexpr ct_sincos_t w = ct_sincos_turns(/*conjugate=*/true, jj * k, IP);
                sr = sr + V(static_cast<T>(w.c)) * tr[jj]
                        - V(static_cast<T>(w.s)) * ti[jj];
                si = si + V(static_cast<T>(w.c)) * ti[jj]
                        + V(static_cast<T>(w.s)) * tr[jj];
            });
            emit(std::integral_constant<std::size_t, k>{}, sr, si);
        });
    }
}

// Same contract as dif_butterfly, for the *last* radix of a pass group, where
// emit is a bare store: the butterfly's own arithmetic dominates, so an odd radix
// with a coprime split takes the twiddle-free PFA. Interior passes must NOT. The
// PFA's serial stage-A -> stage-B chain exposes latency that the flat per-k
// structure of radix_sym_dft hides.
template<typename T, std::size_t IP, typename V, typename Emit>
ADM_ALWAYS_INLINE void dif_butterfly_terminal(const V (&tr)[IP],
                                              const V (&ti)[IP],
                                              Emit&& emit) {
    // 9 is 3*3 (gcd 3), so it has no split and falls through to radix_sym_dft.
    constexpr auto split = coprime_split(IP);
    if constexpr (IP % 2 == 1 && split.first != 0) {
        pfa_dif_butterfly<T, split.first, split.second>(tr, ti,
                                                                 std::forward<Emit>(emit));
    } else {
        dif_butterfly<T, IP>(tr, ti, std::forward<Emit>(emit));
    }
}

// ----------------------------------------------------------------------------
// Register/SIMD-width-derived unroll factor for the vectorized DIF a-loop. U
// independent W-wide butterflies per iteration multiplies the live batch set by
// U, so U caps to stay inside the register file. peak_live = 2*IP + 10 is the
// calibrated upper bound over the symmetric kernel's live set (pair sums/diffs,
// accumulators, twiddle temps); U must produce NO vector spills. U=1 for
// FMA-bound radices; larger U only spills.
template<std::size_t IP>
consteval std::size_t dif_pass_unroll() {
    constexpr std::size_t peak_live = 2u * IP + 10u;
    constexpr std::size_t budget = poet::vector_register_count();
    constexpr std::size_t u = budget / peak_live;
    return u < 1u ? 1u : u;
}

} // namespace detail
} // namespace admiral

#include "undef_macros.hpp"

